export const lodge = {
  name: 'Le Refuge des Ardennes',
  tagline: 'Votre havre de paix au cœur de la forêt ardennaise',
  owners: 'Marie & Thomas Lecomte',
  ownerMessage:
    "Bienvenue au Refuge des Ardennes ! Nous sommes ravis de vous accueillir dans ce lieu qui nous tient tant à cœur. Ce gîte, niché au cœur de la forêt ardennaise, est notre façon de vous offrir une parenthèse de sérénité et de nature. N'hésitez pas à nous contacter pour tout besoin — votre confort et votre bonheur durant ce séjour sont notre priorité.",

  contact: {
    phone: '+32 476 12 34 56',
    email: 'contact@refugedesardennes.be',
    whatsapp: '+32 476 12 34 56',
  },

  address: {
    line1: '15 Chemin des Fougères',
    city: 'La Roche-en-Ardenne',
    postalCode: '6980',
    country: 'Belgique',
    full: '15 Chemin des Fougères, 6980 La Roche-en-Ardenne, Belgique',
    googleMapsLink: 'https://maps.google.com/?q=La+Roche-en-Ardenne,+Belgique',
    mapsEmbed:
      'https://maps.google.com/maps?q=La+Roche-en-Ardenne,+Belgium&t=&z=13&ie=UTF8&iwloc=&output=embed',
  },

  travelTimes: [
    { city: 'Bruxelles', time: '1h45', km: '130 km' },
    { city: 'Luxembourg', time: '1h15', km: '80 km' },
    { city: 'Liège', time: '55 min', km: '70 km' },
    { city: 'Paris', time: '3h30', km: '270 km' },
  ],

  checkIn: {
    arrivalTime: '16:00',
    departureTime: '11:00',
    keyBoxCode: '3847',
    instructions: [
      'Depuis La Roche-en-Ardenne, prendre la N89 direction Vielsalm pendant 4 km.',
      'Tourner à gauche sur le Chemin des Fougères (panneau en bois marron).',
      'Suivre le chemin forestier sur 800 m — le portail en châtaignier est sur votre gauche.',
      'La boîte à clés grise est fixée au mur à droite de la porte d\'entrée.',
      'Entrez le code 3847 — tournez la molette dans le sens horaire, la trappe s\'ouvre.',
      'Laissez-nous un message si vous avez besoin de quoi que ce soit. Bonne arrivée !',
    ],
  },

  wifi: {
    network: 'RefugeArdennes_5G',
    password: 'ForetSauvage2024!',
  },

  amenities: [
    {
      category: 'Confort & Intérieur',
      items: [
        { name: 'Wi-Fi haut débit', icon: 'Wifi' },
        { name: 'Cheminée à bois', icon: 'Flame' },
        { name: 'Chauffage central', icon: 'Thermometer' },
        { name: 'Télévision 65"', icon: 'Tv' },
        { name: 'Bibliothèque', icon: 'BookOpen' },
        { name: 'Jeux de société', icon: 'Gamepad2' },
      ],
    },
    {
      category: 'Cuisine',
      items: [
        { name: 'Cuisine équipée', icon: 'ChefHat' },
        { name: 'Lave-vaisselle', icon: 'Waves' },
        { name: 'Cafetière Nespresso', icon: 'Coffee' },
        { name: 'Raclette & fondue', icon: 'Utensils' },
        { name: 'Cave à vins', icon: 'Wine' },
        { name: 'Micro-ondes & four', icon: 'Zap' },
      ],
    },
    {
      category: 'Extérieur',
      items: [
        { name: 'Terrasse en bois', icon: 'TreePine' },
        { name: 'Barbecue Weber', icon: 'Flame' },
        { name: 'Salon de jardin', icon: 'Armchair' },
        { name: 'Hamac', icon: 'Moon' },
        { name: 'Parking privé ×3', icon: 'Car' },
        { name: 'Bûches incluses', icon: 'Logs' },
      ],
    },
    {
      category: 'Bien-être & Sport',
      items: [
        { name: 'Sauna finlandais', icon: 'Thermometer' },
        { name: 'Jacuzzi extérieur', icon: 'Droplets' },
        { name: 'Vélos ×4', icon: 'Bike' },
        { name: 'Lave-linge + séchoir', icon: 'RefreshCw' },
        { name: 'Équipement rando', icon: 'MapPin' },
        { name: 'Détecteur & extincteur', icon: 'ShieldCheck' },
      ],
    },
  ],

  houseRules: [
    { icon: 'CigaretteOff', text: 'Propriété non-fumeur (terrasse autorisée)' },
    { icon: 'PartyPopper', text: 'Pas de fête ni rassemblement > 12 personnes' },
    { icon: 'Moon', text: 'Silence à partir de 22h30' },
    { icon: 'Dog', text: 'Animaux bienvenus (signaler à l\'avance)' },
    { icon: 'Recycle', text: 'Tri sélectif obligatoire — conteneurs à l\'entrée' },
    { icon: 'Flame', text: 'Feu de cheminée avec pare-feu uniquement' },
    { icon: 'Droplets', text: 'Merci de limiter la durée des douches' },
    { icon: 'KeyRound', text: 'Départ : vaisselle faite, poubelles vidées' },
    { icon: 'Leaf', text: 'Respect de la faune et flore environnantes' },
    { icon: 'Lock', text: 'Fermer fenêtres et portes en partant' },
  ],

  activities: [
    {
      name: 'Descente de l\'Ourthe en kayak',
      category: 'Eau',
      distance: '2,5 km',
      duration: '2h–3h',
      description:
        'La classique des Ardennes ! Location de kayaks à La Roche, descente jusqu\'à Maboge.',
      phone: '+32 84 41 13 59',
      icon: 'Waves',
      highlight: true,
    },
    {
      name: 'Sentier de la Roche Percée',
      category: 'Randonnée',
      distance: '3 km',
      duration: '1h30',
      description:
        'Vue panoramique sur La Roche-en-Ardenne et le méandre de l\'Ourthe.',
      icon: 'Mountain',
      highlight: true,
    },
    {
      name: 'Château de La Roche-en-Ardenne',
      category: 'Culture',
      distance: '3 km',
      duration: '1h–2h',
      description: 'Ruines médiévales du XI\u1d49 siècle avec vue imprenable sur la ville.',
      phone: '+32 84 41 12 81',
      icon: 'Landmark',
    },
    {
      name: 'Grottes de Han',
      category: 'Nature',
      distance: '22 km',
      duration: 'Demi-journée',
      description: 'L\'un des plus beaux sites souterrains d\'Europe. Safari animalier inclus.',
      phone: '+32 84 37 72 13',
      icon: 'MapPin',
    },
    {
      name: 'Château de Bouillon',
      category: 'Culture',
      distance: '40 km',
      duration: 'Demi-journée',
      description: 'Château fort médiéval dominant la Semois — idéal en famille.',
      icon: 'Landmark',
    },
    {
      name: 'Ski de fond – Baraque de Fraiture',
      category: 'Hiver',
      distance: '30 km',
      duration: 'Journée',
      description: 'Le plus grand domaine de ski de fond de Belgique en saison hivernale.',
      icon: 'Snowflake',
    },
  ],

  restaurants: [
    {
      name: 'La Halle de La Roche',
      cuisine: 'Cuisine ardennaise',
      address: '2 Place du Bronze, La Roche-en-Ardenne',
      phone: '+32 84 41 13 31',
      distance: '3,2 km',
      hours: 'Mer–Dim 12h–14h30, 18h–21h30',
      price: '€€',
      specialty: 'Gibier des Ardennes, pâté gaumais',
      recommended: true,
    },
    {
      name: 'Le Cor de Chasse',
      cuisine: 'Brasserie belge',
      address: 'Rue Rompré 3, La Roche-en-Ardenne',
      phone: '+32 84 41 18 44',
      distance: '3,5 km',
      hours: 'Tous les jours 11h–22h',
      price: '€€',
      specialty: 'Carbonade flamande, moules-frites',
      recommended: true,
    },
    {
      name: 'Brasserie de l\'Ourthe',
      cuisine: 'Bistronomie',
      address: 'Quai de l\'Ourthe 12, La Roche-en-Ardenne',
      phone: '+32 84 41 22 10',
      distance: '3,8 km',
      hours: 'Jeu–Lun 12h–14h, 18h–21h',
      price: '€€€',
      specialty: 'Truites de rivière, fromages locaux',
      recommended: false,
    },
    {
      name: 'Le Moulin de La Roche',
      cuisine: 'Gastronomique',
      address: 'Route de Houffalize 8, La Roche-en-Ardenne',
      phone: '+32 84 41 05 68',
      distance: '4,5 km',
      hours: 'Ven–Dim 19h–21h30 (réservation conseillée)',
      price: '€€€€',
      specialty: 'Menu dégustation, gibier en saison',
      recommended: false,
    },
    {
      name: 'La Pizzeria du Château',
      cuisine: 'Pizza & pasta',
      address: 'Rue du Château 1, La Roche-en-Ardenne',
      phone: '+32 84 41 12 05',
      distance: '3,3 km',
      hours: 'Tous les jours 12h–22h',
      price: '€',
      specialty: 'Pizzas au feu de bois',
      recommended: false,
    },
  ],

  walks: [
    {
      name: 'Sentier des Panoramas',
      type: 'hiking',
      distance: '8,5 km',
      duration: '2h30',
      difficulty: 'Moyen',
      difficultyColor: 'amber',
      startPoint: 'Parking du Pont de l\'Ourthe',
      elevation: '+320 m',
      description:
        'Le tour classique de La Roche — les plus beaux points de vue sur les méandres de l\'Ourthe et les falaises ardennaises.',
      highlights: ['Rocher du Corby', 'Panorama de Berismenil', 'Belvédère Culot'],
    },
    {
      name: 'Balade des Sources',
      type: 'hiking',
      distance: '5 km',
      duration: '1h30',
      difficulty: 'Facile',
      difficultyColor: 'green',
      startPoint: 'Au départ du gîte',
      elevation: '+80 m',
      description:
        'Promenade tranquille en sous-bois le long d\'un ruisseau. Idéale pour les enfants et les débutants.',
      highlights: ['Cascade du Ruisseau des Fougères', 'Hêtraie centenaire', 'Pont médiéval en bois'],
    },
    {
      name: 'Circuit VTT des Crêtes',
      type: 'cycling',
      distance: '32 km',
      duration: '2h30',
      difficulty: 'Difficile',
      difficultyColor: 'red',
      startPoint: 'Parking du gîte',
      elevation: '+850 m',
      description:
        'Pour les vététistes chevronnés — un tour magnifique à travers les crêtes ardennaises avec des descentes techniques.',
      highlights: ['Vue sur la Baraque Fraiture', 'Village de Nadrin', 'Descente vers Maboge'],
    },
    {
      name: 'Véloroute de l\'Ourthe',
      type: 'cycling',
      distance: '18 km',
      duration: '1h30',
      difficulty: 'Facile',
      difficultyColor: 'green',
      startPoint: 'Pont de La Roche-en-Ardenne',
      elevation: '+120 m',
      description:
        'Piste cyclable longeant l\'Ourthe, quasi entièrement plate. Parfaite pour une sortie en famille.',
      highlights: ['Berges de l\'Ourthe', 'Village de Hotton', 'Champs de lupins (juin)'],
    },
  ],

  emergencies: {
    numbers: [
      {
        name: 'Urgences européennes',
        number: '112',
        color: 'red',
        description: 'Appel gratuit, 24h/24',
      },
      {
        name: 'Police',
        number: '101',
        color: 'blue',
        description: 'Police fédérale belge',
      },
      {
        name: 'Pompiers / SAMU',
        number: '100',
        color: 'orange',
        description: 'Urgences médicales',
      },
      {
        name: 'Centre Anti-Poisons',
        number: '070 245 245',
        color: 'yellow',
        description: '24h/24, 7j/7',
      },
    ],
    hospital: {
      name: 'Clinique Saint-Joseph',
      address: 'Rue de Rompré 2, 6980 La Roche-en-Ardenne',
      phone: '+32 84 41 21 11',
      distance: '4,5 km',
    },
    pharmacy: {
      name: 'Pharmacie de l\'Ourthe',
      address: 'Place du Marché 5, La Roche-en-Ardenne',
      phone: '+32 84 41 10 88',
      hours: 'Lun–Ven 8h30–18h30 / Sam 9h–13h',
      distance: '3,5 km',
    },
    doctor: {
      name: 'Dr François Mathieu',
      address: 'Rue Rompré 15, La Roche-en-Ardenne',
      phone: '+32 84 41 14 22',
      hours: 'Lun–Ven 8h–18h (sur RDV)',
      distance: '3,2 km',
    },
    owner: {
      name: 'Marie Lecomte (propriétaire)',
      phone: '+32 476 12 34 56',
      email: 'contact@refugedesardennes.be',
    },
  },

  gallery: [
    { id: 1018, seed: '1018', caption: 'Vue sur la vallée ardennaise', category: 'Nature', aspect: 'landscape' },
    { id: 1040, seed: '1040', caption: 'Façade du refuge en automne', category: 'Extérieur', aspect: 'landscape' },
    { id: 1043, seed: '1043', caption: 'Salon avec cheminée en pierre', category: 'Intérieur', aspect: 'landscape' },
    { id: 1060, seed: '1060', caption: 'Allée forestière menant au gîte', category: 'Nature', aspect: 'portrait' },
    { id: 1011, seed: '1011', caption: 'Terrasse avec vue sur la forêt', category: 'Extérieur', aspect: 'landscape' },
    { id: 1015, seed: '1015', caption: 'Chambre principale en bois clair', category: 'Intérieur', aspect: 'portrait' },
    { id: 1048, seed: '1048', caption: 'Jacuzzi extérieur au coucher du soleil', category: 'Bien-être', aspect: 'landscape' },
    { id: 1053, seed: '1053', caption: 'Brume matinale sur la forêt', category: 'Nature', aspect: 'landscape' },
    { id: 1025, seed: '1025', caption: 'Barbecue en bois sur la terrasse', category: 'Extérieur', aspect: 'landscape' },
    { id: 1036, seed: '1036', caption: 'Sauna finlandais traditionnel', category: 'Bien-être', aspect: 'portrait' },
  ],
}
